### ISSUE TITLE
query re: PHP EOL policy

### ISSUE THREAD

**Issue by SignpostMarv** [paragonie/easydb#123]
Should a PR for bumping up the minimum PHP version (inline with [your current versions policy](https://paragonie.com/blog/2016/04/go-php-7-our-commitment-maintaining-our-open-source-projects)) jump straight from 7.0 to 7.2, or first make commits for 7.0 to 7.1 ?

**Comment by paragonie-security** [comment]
If we want to tag a version 3 of the library, we can set the minimum to 7.3 when that happens. (Or if it's much later, 7.4 or 8.0).

Following the "only current versions" policy has become less urgent since the part of the ecosystem that has successfully jettisoned PHP 5 support is largely excellent at moving to 7.LATEST within the first year of its availability.
