### ISSUE TITLE
Version 2.0.0

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/easydb#13]
I should be releasing version 2 before tomorrow. If anyone would care to give me feedback on the changes I've made this evening, please do.

**Comment by SignpostMarv** [comment]
I was wondering if this should throw an exception/ log a warning?
```php
$db = new EasyDB($pdo);
$db->setAttribute(\PDO::ATTR_EMULATE_PREPARES, true);
```

**Comment by paragonie-scott** [comment]
Yes, that would be a good idea :)

**Comment by SignpostMarv** [comment]
In that case, would the clone statement you added negate the issue of $db->getPdo()->setAttribute() bypassing EasyDB ?

**Comment by paragonie-scott** [comment]
Yes, it would. You'd have a cloned instance of the internal PDO but be unable to affect the PDO object used by EasyDB.

**Comment by SignpostMarv** [comment]
re: code style consistency commits & static analyses commits, are the tools you use available as gpg-signed binaries as with the phpunit runner ?

**Comment by paragonie-scott** [comment]
I'm actually just using PHPStorm's built in inspections, as I've found it to be as reliable as most third party tools.

**Comment by SignpostMarv** [comment]
I use Atom at home/work, although I run php-cs-fixer from cli rather than the atom package- the .editorconfig from #11 is another habit I got into so I don't break style between machines/projects.

**Comment by SignpostMarv** [comment]
I'm guessing the only benefit to automated linting on travis is to fail a pull request if someone doesn't meet your preferred coding style.

**Comment by paragonie-scott** [comment]
I prefer the @hintjens approach: Merge and fix the code style ourselves. :)

**Comment by SignpostMarv** [comment]
:)

[Since we're already throwing exceptions](https://github.com/paragonie/easydb/blob/53e3b7026093ca18ff3b9851eea7f613e2086d3d/src/EasyDB.php#L156) if ```$string``` is empty or starts with a number, should we be throwing an exception in EasyDB::escapeIdentifier() if ```$str !== trim($string)``` (or ```$str !== $string``` for the even more paranoid approach)?
i.e. ```$str``` refers to something other than ```$string``` (since "foo@bar" ≠ "foobar") vs "your ```$string``` is terrible"? (possible overkill on the input paranoia there :P)

Furthermore, is it overkill to modify it further to support separator characters when quoting? i.e.
```php
$db = new EasyDB($pdo);

 // would normally return [foobar], "foobar" or `foobar`
$tableThenField = $db->escapeIdentifier('foo.bar');

// would normally return [foobarbaz], "foobarbaz" or `foobarbaz`
$databaseThenTableThenField = $db->escapeIdentifier('foo.bar.baz');
```

p.s. since the linux box is currently segfaulting on php making testing a pain, I'll be off for the night- fingers crossed that the my main system works tomorrow when it comes back from repair tomorrow.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/easydb/commit/6c28b21b6bba69c73a429ba863142926a601c546

I've made separator support optional. To enable it, `$edb->setAllowSeprators(true);`.

**Comment by SignpostMarv** [comment]
I've found some bugs in the tests etc., will push them up later
