### ISSUE TITLE
Installation / use?

### ISSUE THREAD

**Issue by akak0r** [paragonie/easydb#45]
Hi,
can you maybe add a short installation how-to for people not using Composer? Not everyone has his/her own server, I'm using shared hosting.
Thanks.

**Comment by paragonie-scott** [comment]
Composer doesn't require your own server.

Just follow [the steps on the Composer website](https://getcomposer.org/download/).

**Comment by akak0r** [comment]
But I can't install it on shared hosting. Just locally (which is Windows and I will end up with different paths),
So maybe you can do it like PHPMailer: show how to install it using composer, and how to do it manually. Not everyone is an expert.

**Comment by paragonie-scott** [comment]
> But I can't install it on shared hosting.

You should be able to. You don't need special privileges. You don't need a C compiler.

Heck, you could just download the `.phar` file from their website then run:

```sh
php composer.phar require paragonie/easydb
```

**Comment by akak0r** [comment]
There's no command line (ssh) on shared hosting... so no, that is not possible. Otherwise, I wouldn't have asked. Instead of all these answers, I guess you could have just written how to use it without composer, like I asked. But your message is clear.

**Comment by tuupola** [comment]
Install with composer on your development machine and then ftp everything (including the vendor folder created by composer) to the shared host.

**Comment by paragonie-scott** [comment]
> There's no command line (ssh) on shared hosting... so no, that is not possible.

Okay, this is surprising to me. Every shared hosting provider I've ever used in my life at least offered SSH access. Setting it up was usually buried inside of cPanel, but it was still available.

> Instead of all these answers, I guess you could have just written how to use it without composer, like I asked. But your message is clear.

Satisfying the "can't use Composer" use-case is nontrivial. We did it with random_compat, and Taylor Hornby did it with his encryption library.

Since most of the world has moved onto Composer, it becomes a question of whether we want to expend the effort on our end to build and maintain a .phar release, or apply market pressure to hosting providers to allow Composer support. That's a discussion that can be had.

**Comment by PeeHaa** [comment]
I agree that people should just use composer, but what's nontrivial about adding a simple autoloader for a stand alone package like this?

Again not saying you should at all, just scratching my head what makes it nontrivial.

**Comment by paragonie-scott** [comment]
My main reason for not wanting to do this is that it encourages people to run out-of-date versions of our code, which nobody should ever do, especially if a security vulnerability is discovered in a previous version.

**Comment by PeeHaa** [comment]
I get that. Was just wondering about the nontrivial argument :-)

**Comment by paragonie-scott** [comment]
We've addressed the deficit (no clear install instructions) on the README: https://github.com/paragonie/easydb#installing-easydb

If you can't use Composer because no SSH access, I recommend migrating to a different provider. [Low-End Box](https://lowendbox.com) is a great resource for web hosting on a budget. If a VPS isn't viable and your shared hosting provider won't grant you SSH access, other shared hosting providers do offer SSH access. (Off the top of my head, A1 Hosting, GoDaddy, and BlueHost all definitely do.)

**Comment by dougcassidy** [comment]
Cant you just require_once all the files?

**Comment by smalos** [comment]
> Cant you just require_once all the files?

Yes, should work just to include those files. Maybe also include the files from /corner if required.
```
require_once('EasyDB.php');
require_once('EasyStatement.php');
require_once('EasyPlaceholder.php');
require_once('Factory.php');

```
