### ISSUE TITLE
How is the right way with row function and multi parameters ?

### ISSUE THREAD

**Issue by DLX23** [paragonie/easydb#93]
i try:
`$db->row("SELECT * FROM customers WHERE email = ? AND actkey = ?",array($email,$actkey));`
but it don't work. Error comes up :  Only one-dimensional arrays are allowed,
what did i wrong ?

**Comment by paragonie-scott** [comment]
```diff
- $db->row("SELECT * FROM customers WHERE email = ? AND actkey = ?",array($email,$actkey))
+ $db->row("SELECT * FROM customers WHERE email = ? AND actkey = ?", $email, $actkey))
```

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/easydb/commit/abe995bb8a24961ca4dbd027f344321c4704f028

I've updated the README to make these details easier to find: https://github.com/paragonie/easydb/blob/master/README.md#fetch-a-single-row-from-a-table

**Comment by DLX23** [comment]
Thank You!
There is a way to debug ? can i show the complete query from $db->row ?

**Comment by paragonie-scott** [comment]
I don't understand your question.

If you're asking what I *suspect* you're asking...

EasyDB doesn't build a query string. It sends the query string to the database, then sends the parameters in a separate packet. This process is called **prepared statements**, and is a provably secure way to prevent the query parameters (data) from mutating the query string (code).

There is no "debug" feature because we're not doing any string manipulation. The string you pass EasyDB is the string that gets passed to your database.

**Comment by DLX23** [comment]
thank you very much!!! your're right, my fail. it works very good.
i have another question to the update function

```
$db->update('comments', [
    'approved' => true
], [
    'commentid' => $_POST['comment']
]);
```
i dont know what is which field?
if i do in mysql:
```
UPDATE Customers
SET ContactName = 'Max Muster', City= 'Berlin'
WHERE CustomerID = 1;
```

what is it in easyDB ?

`$db->update('Customers', ['ContactName' => "1"], ['City' => 'Berlin']);`
And where must i place "WHERE CustomerID=1" ?

**Comment by paragonie-scott** [comment]
The API is `update($table, $fieldsToUpdate, $conditions)`.

So you'd want to do this:

```php
$db->update(
    'Customers',
    ['ContactName' => "1", 'City' => 'Berlin']
    ['CustomerID' => 1]
);
```

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/easydb/commit/0ac58c947070f2fd6ab4dc01a097c23a12581c20 

The README explains this more clearly. Thanks for opening the issue.
